# Generated by Django 6.0.4 on 2026-04-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderitem_product_name_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('hazirlaniyor', 'Hazırlanıyor'), ('kargoya_verildi', 'Kargoya Verildi'), ('yolda', 'Yolda'), ('teslim_edildi', 'Teslim Edildi')], default='hazirlaniyor', max_length=20, verbose_name='Sipariş Durumu'),
        ),
    ]
